<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Draft</name>
   <tag></tag>
   <elementGuidId>5ff1611b-9bb8-45fd-b356-529f256f2400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-stage-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-stage-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06a1625b-5b43-4e5f-bd0e-bd2ad4363fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>cc43509f-a65a-4f5a-957d-3b76b7d94c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-stage-container</value>
      <webElementGuid>1263da45-9451-446c-8bfb-62360ca081fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Draft   </value>
      <webElementGuid>b0379367-581e-4923-b177-2e6d237ca215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft   </value>
      <webElementGuid>62d8f561-0315-443f-85dd-28b853c79e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-stage-container&quot;)</value>
      <webElementGuid>fae249e4-cdbe-4121-bb72-3611838e76d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-stage-container']</value>
      <webElementGuid>cc65be19-bd5f-44df-8a62-e12fd3b07729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/form/div/div/div[2]/div[4]/div/span/span/span/span</value>
      <webElementGuid>d63ac616-73ee-44e3-97a2-a7f223c805a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[3]/following::span[6]</value>
      <webElementGuid>ec83a616-adc2-471d-8dbb-a30a3c490e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[2]/preceding::span[3]</value>
      <webElementGuid>be5ae324-26a8-402e-9986-bf5820053fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Name'])[1]/preceding::span[3]</value>
      <webElementGuid>d1183080-b0b3-4d8e-9d5a-3625d80c5401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>650b6a29-6f0a-4819-8600-a0c0577c2ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-stage-container' and @title = 'Draft   ' and (text() = 'Draft   ' or . = 'Draft   ')]</value>
      <webElementGuid>d1f31a9a-a28d-48ab-82e7-53c22df94437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
