<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed</name>
   <tag></tag>
   <elementGuidId>9aed6e54-3800-4f7b-a03d-fdeb03430a5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#butSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='butSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52f7e653-6b41-4d4f-8ca9-5f8b0dde7465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4dadbc42-a873-48c1-adde-2d49b5506860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>1c323222-c5ce-4096-9b25-9c31b61af813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>button.save</value>
      <webElementGuid>72c36d2a-5b56-4e52-aaae-3f4b90c6ba0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>theme</name>
      <type>Main</type>
      <value>simple</value>
      <webElementGuid>0de7c95b-5e40-428a-92ce-a0e5a7607c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>butSave</value>
      <webElementGuid>9c4c9949-6ea1-4de9-933b-23a7155b2a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								 Proceed
							</value>
      <webElementGuid>b0180d4c-89e7-4fcc-aa33-72e550b22c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;butSave&quot;)</value>
      <webElementGuid>accb68bb-eba0-4b9d-a2df-fd747c6ff8da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='butSave']</value>
      <webElementGuid>8d638711-a3ed-4f06-941e-690ee80b9172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/form/div[2]/div/button[2]</value>
      <webElementGuid>f71ac17f-c707-4717-a9cd-9e825a1d04be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Terms:'])[1]/following::button[2]</value>
      <webElementGuid>b53f2b18-b33f-4f63-aa2b-883e237c6993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firestone Destination A/T GRIP'])[3]/preceding::button[2]</value>
      <webElementGuid>7efcc597-1778-49de-9fbc-9e7033f00766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sizing'])[2]/preceding::button[2]</value>
      <webElementGuid>7c56fa1a-fe53-4d8a-9032-be0a6af4f368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed']/parent::*</value>
      <webElementGuid>202df791-6221-41dc-a393-df0370c791d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5e7fcdbd-900a-4e54-8fa8-0e2c01bd70e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'butSave' and (text() = '
								 Proceed
							' or . = '
								 Proceed
							')]</value>
      <webElementGuid>fe0894c8-8db2-43bc-882c-660cfad1f471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
