<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quotation No_quotationNo</name>
   <tag></tag>
   <elementGuidId>a2fb58f3-cd11-4544-a52d-78d59dc26ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quotationNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='quotationNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44dae0ea-0116-407a-a91b-a0e753b849fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f27d72fe-6ff3-493c-8180-0c1f53f10ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quotationNo</value>
      <webElementGuid>df16ad23-e290-4bbe-a39b-e0e0d7c2948f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>388f59dc-67fc-46d0-ab5d-63050d3f8b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quotationNo</value>
      <webElementGuid>53b25bea-5234-4e08-ab15-2a72da68b3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Quotation No</value>
      <webElementGuid>b9fff9e3-7084-4cfa-a4e2-4b810fb5ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1670066347056</value>
      <webElementGuid>47d956fc-db7e-4bb6-9f35-ee3d933fbc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>36b06ac5-fdf4-41d1-8e1e-eaba171c2452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quotationNo&quot;)</value>
      <webElementGuid>0960779e-6690-44d2-bb1f-a8540677a532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quotationNo']</value>
      <webElementGuid>632cd237-4049-400b-a938-7befd9e21231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/form/div/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>5bc47ce4-4d1b-476d-9032-22c5ef10b657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]/div/input</value>
      <webElementGuid>4339941f-05fc-434b-9d47-5c5bd5ff6a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'quotationNo' and @id = 'quotationNo' and @placeholder = 'Quotation No']</value>
      <webElementGuid>57e1b5c7-f476-4958-9f47-3865afb3f3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
