<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search-contact</name>
   <tag></tag>
   <elementGuidId>488f42d3-fa8d-4f48-b363-6fa5645994ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-contactNameSelect-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-contactNameSelect-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>80b14776-e700-4a77-9c92-9778588e83a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b8f48214-29d4-455d-b6ef-57c2a7e42de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-contactNameSelect-container</value>
      <webElementGuid>1d44b32c-ce65-462f-adeb-224eeea5c2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6bd935fd-f053-4790-88f8-ffb450b3425f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-contactNameSelect-container&quot;)</value>
      <webElementGuid>83dbeada-1811-4281-9a81-7a3ac35329b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-contactNameSelect-container']</value>
      <webElementGuid>cd2c4d24-b106-4002-b063-4ebe790950a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/form/div/div/div/div/div/div/span/span/span/span</value>
      <webElementGuid>ff899087-de17-4ab1-b30d-a3929d9a0673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/following::span[4]</value>
      <webElementGuid>c63481d9-0c28-42c7-8c54-59127cd6680c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quotation'])[2]/following::span[4]</value>
      <webElementGuid>6652e078-d6c8-4013-b185-b1a3ca95eacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>e80e8764-3738-420f-803c-8d3ce90edb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-contactNameSelect-container' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>7ccf2287-502a-4078-a52c-d8e0ca038083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
