<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Deal</name>
   <tag></tag>
   <elementGuidId>9a22e87d-b58c-496a-8e27-465c5ce61497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-dealName-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-dealName-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>899b8317-cad0-42aa-a7b4-3481e96f5564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>3414952a-d410-47d0-89ac-2261f2d777ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-dealName-container</value>
      <webElementGuid>29ee0f7c-9cc7-4a1c-b79e-96af3b384443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deal</value>
      <webElementGuid>83285ad5-e89d-4822-bd70-2f47a5780b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-dealName-container&quot;)</value>
      <webElementGuid>db772bfd-3dd8-4b87-aa7f-cdff888da064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-dealName-container']</value>
      <webElementGuid>4b05b5f4-e4da-400b-9c24-5f9121bb109d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/form/div/div/div[2]/div[2]/span/span/span/span</value>
      <webElementGuid>b2f06d45-b569-4715-8a82-231ec3306815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deal'])[2]/following::span[4]</value>
      <webElementGuid>c72a05ab-0779-41b4-b86c-dbd875232072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[1]/preceding::span[4]</value>
      <webElementGuid>4897da89-48cd-47fa-9093-fce77fdb8ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>c8ccdd74-1b58-480e-b289-3a0c4a056856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-dealName-container' and (text() = 'Deal' or . = 'Deal')]</value>
      <webElementGuid>02c99ea4-ff5e-409b-8da5-ec510956ad9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
