<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Draft</name>
   <tag></tag>
   <elementGuidId>124235d8-5130-4613-ad6c-5e24b604580e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-stage-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-stage-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3bce7533-2a52-4c22-9f92-01363fa0edfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e08282c2-1bc8-4c44-bc29-ee3d52f734a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-stage-container</value>
      <webElementGuid>bca0eab3-b69f-4a5e-9cfe-7f62a30360c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Draft   </value>
      <webElementGuid>18c4cff5-9293-4c14-8891-4e9b06616d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft   </value>
      <webElementGuid>70d4e9ef-dc90-4767-ad2b-f94f9ad3cede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-stage-container&quot;)</value>
      <webElementGuid>6164aef9-6ea2-44b0-9dcb-b3a785bfd334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-stage-container']</value>
      <webElementGuid>78e311a9-4e52-4d81-80a4-b0ee68ece871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/form/div/div/div[2]/div[4]/div/span/span/span/span</value>
      <webElementGuid>a4a1efb8-cefb-46ae-8fe2-e4b58b8b9124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[3]/following::span[6]</value>
      <webElementGuid>1a718f7d-676b-42f5-bf40-b2fe6c0224dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[2]/preceding::span[3]</value>
      <webElementGuid>07e6c244-f5d5-48f6-ade7-518b19d98a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Name'])[1]/preceding::span[3]</value>
      <webElementGuid>d909996a-3b83-4856-91c5-0a94e2108152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>acaac5e1-f481-46e0-985c-4e94f0cc5092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-stage-container' and @title = 'Draft   ' and (text() = 'Draft   ' or . = 'Draft   ')]</value>
      <webElementGuid>4eaaeb51-d784-4b34-aaac-8ab90f66f9bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
