<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search-account</name>
   <tag></tag>
   <elementGuidId>c12f7143-c563-45bb-8ef2-ac7e695c8d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-accountNameSelect-container > span.select2-selection__placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-accountNameSelect-container']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2094d05f-ea6d-4605-baee-a4b102244846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>ce194e03-0182-49e7-98dd-73b92f717595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6ce2960d-1bb2-48e5-b062-4c7c7eed1e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-accountNameSelect-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>74ae8d53-894a-4985-98e8-9c023f2b5012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-accountNameSelect-container']/span</value>
      <webElementGuid>b6d61296-203c-4683-b3a5-1e10747e4c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/following::span[5]</value>
      <webElementGuid>f2164511-ea04-4742-b1b3-06e99b6eda02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span/span</value>
      <webElementGuid>623a67e2-c38d-4829-9c36-d7141e0e4d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>681f1fbd-6ffb-4e6e-bbe1-8ee13f05e0c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
