<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_26570R16</name>
   <tag></tag>
   <elementGuidId>9b40402f-98e6-4ce6-bd5e-3ba1aa5bcf85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.0p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='sizingTablerow0']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ed5c7af9-1733-4094-a9e9-edc771cad132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>0p</value>
      <webElementGuid>7e39373a-94e3-44fe-9bcd-c1587ba15da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>265/70R16</value>
      <webElementGuid>167f03b6-37fa-4c68-8fe0-b3fa7ca01cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sizingTablerow0&quot;)/td[@class=&quot;0p&quot;]</value>
      <webElementGuid>5ce646df-bd13-4836-a567-d69b2020c309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='sizingTablerow0']/td</value>
      <webElementGuid>f0dd501d-d471-4d91-abf1-e32446c96d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[2]/following::td[1]</value>
      <webElementGuid>edbfb411-5254-4827-8136-a5bb5748b59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[2]/following::td[1]</value>
      <webElementGuid>9487f28d-87e8-4500-a4fd-8ca095a5a8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::td[15]</value>
      <webElementGuid>2635d43c-b435-4a7b-bad3-f940f03a9456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save changes'])[1]/preceding::td[15]</value>
      <webElementGuid>d14cfa9e-6369-4a90-9cf6-d5082dc48d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='265/70R16']/parent::*</value>
      <webElementGuid>1ccdc7d2-8c17-404d-93a6-3eebf9354116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>c4531fc6-3443-4401-8be0-642a2d0c35cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '265/70R16' or . = '265/70R16')]</value>
      <webElementGuid>e7442256-2b70-4305-97fc-6c4fc6daeb69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
