<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Associate With Account Records_fa fa-search</name>
   <tag></tag>
   <elementGuidId>37773042-fde2-40eb-8949-4eb0ed7f6658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accounts']/div/div/div[2]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accounts > div.panel-body > div.row > div.form-group.form-group-header.col-lg-3.col-md-3.col-sm-3.col-xs-3 > button.btn.btn-default.btng-right > i.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>70b5c02d-d2f3-4ac8-adb8-53a3610c6336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>b35eab20-77d1-41a0-ab0f-c2703dde95d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accounts&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group form-group-header col-lg-3 col-md-3 col-sm-3 col-xs-3&quot;]/button[@class=&quot;btn btn-default btng-right&quot;]/i[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>cd50173e-ac93-4129-a8c6-30431bbbe26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accounts']/div/div/div[2]/button/i</value>
      <webElementGuid>f805c95c-85fb-491d-83a3-5822755d8b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/div/div[2]/button/i</value>
      <webElementGuid>f1f792df-cd0d-4253-bd34-686221177ed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
