<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_LowMediumHigh</name>
   <tag></tag>
   <elementGuidId>90f87e01-a310-47b8-8f66-28c89cd3ca0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dealPriority']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dealPriority</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f5a53646-f921-415a-b7d4-6ace280eac71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-placeholer form-control</value>
      <webElementGuid>9780f8e1-2705-4469-97f2-ffa61892cbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dealPriority</value>
      <webElementGuid>058fcc9b-89a3-4ae4-a7ad-eebb53e52f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dealPriority</value>
      <webElementGuid>6c08671a-1800-4e80-beff-4dab47f81037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Medium</value>
      <webElementGuid>015ce249-379c-406f-a9f1-84c514c9c4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											Low
											Medium
											High
										</value>
      <webElementGuid>b8ceca6f-4729-4a91-bf6d-cd4b93f6b107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealPriority&quot;)</value>
      <webElementGuid>01d03738-3ef9-417c-9ed0-c46c78ac5625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dealPriority']</value>
      <webElementGuid>f450d98f-9664-41c6-a3e8-510031b32a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dealFormId']/div/div[8]/select</value>
      <webElementGuid>4ee5c63f-b244-4cf0-9904-c3c5061497cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::select[1]</value>
      <webElementGuid>5d13bd2b-c94d-4fcd-bf96-2c38f2a79a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>600123ec-ea9c-4261-bf6e-01c5fd89d73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associate With Account Records'])[1]/preceding::select[1]</value>
      <webElementGuid>c6693949-1adb-498a-a194-51ff8c12a684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search to load Accounts'])[1]/preceding::select[1]</value>
      <webElementGuid>4904b8fd-65a4-40e8-a85f-29ed600998a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>9a5a8acf-6e60-49fc-b266-f3f0249fce57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dealPriority' and @name = 'dealPriority' and (text() = '
											Low
											Medium
											High
										' or . = '
											Low
											Medium
											High
										')]</value>
      <webElementGuid>8c249eed-c5e6-4afc-a891-a7478d7f76b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
