<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Associate With Contact Records_fa fa-search</name>
   <tag></tag>
   <elementGuidId>0a4773e6-79cc-446f-92ce-d7efb8ebac53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contacts']/div/div/div[2]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contacts > div.panel-body > div.row > div.form-group.form-group-header.col-lg-3.col-md-3.col-sm-3.col-xs-3 > button.btn.btn-default.btng-right > i.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c917cee2-c42d-4c0f-b440-b0ad6cac4b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>b02e6516-3b8f-415d-8ae9-ff0d5cc08ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contacts&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group form-group-header col-lg-3 col-md-3 col-sm-3 col-xs-3&quot;]/button[@class=&quot;btn btn-default btng-right&quot;]/i[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>7e8f19cd-b516-4be7-8009-ae74ef1d247d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contacts']/div/div/div[2]/button/i</value>
      <webElementGuid>6d2ba67c-e7a5-4527-8a90-1ae40232b5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/div/div/div[2]/button/i</value>
      <webElementGuid>cf51672c-f2da-47c0-8e67-289fc77a6403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
