<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Dashboard Forecast</name>
   <tag></tag>
   <elementGuidId>b35bd320-3219-4519-8928-0f6899eb7dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.grey-fade.mb0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontent']/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>3b3fb0d8-54b0-4f05-ad32-5978127ca9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey-fade mb0</value>
      <webElementGuid>52a6df38-abe3-42a8-8a13-4f55186f0511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard 
				Forecast
			</value>
      <webElementGuid>b35a6279-b0aa-485d-b8dd-a76d8ed587b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;container-fluid dashboard&quot;]/h3[@class=&quot;grey-fade mb0&quot;]</value>
      <webElementGuid>6bc61367-161f-46dc-9391-220a05a4f5fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/h3</value>
      <webElementGuid>fdccfdc9-87ca-405a-80e4-18ecb359444e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::h3[1]</value>
      <webElementGuid>6a6521c9-358a-4573-a3b8-0522290fcd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='America/Detroit'])[1]/following::h3[1]</value>
      <webElementGuid>49aef399-c859-45e5-bcd2-5d8f6f337ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top 5 Account'])[1]/preceding::h3[1]</value>
      <webElementGuid>feef2531-fe7a-4ce9-951b-193516218104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>73157213-e126-4fa9-9a5e-d676dce1a763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Dashboard 
				Forecast
			' or . = 'Dashboard 
				Forecast
			')]</value>
      <webElementGuid>29ed8435-d82f-45f2-a759-109e0eb3ab54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
